//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Company_id { get; set; }
        public int Admin_id { get; set; }
        public int Branch_id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fathers_Name { get; set; }
        public string Mothers_Name { get; set; }
        public string Spouse_Name { get; set; }
        public byte[] Profile_Image { get; set; }
        public string NID { get; set; }
        public string Passport { get; set; }
        public string District { get; set; }
        public string Working_outlet { get; set; }
        public string cell { get; set; }
        public string Address { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public string Present_address { get; set; }
        public string Permanent_address { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Reference { get; set; }
        public string Reference_Name { get; set; }
        public string Reference_last_edu { get; set; }
    }
}
